### ISSUE TITLE
Sign up Flow

### ISSUE THREAD

**Issue by Elam126** [venzo-tech/Saymingo#16]
The bottom button should be the same height for all the screens (Sign up flow).

All the screens should be responsive.

**Comment by sivasakthi26** [comment]
#16
signup button
lib/Pages/Login & Signup/signup.dart
![signup](https://github.com/venzo-tech/Saymingo/assets/104203753/887fa756-5962-4e0a-89d4-6ee5af6a4da8)

the bottom button should be the same height for otp screen
lib/Pages/Login & Signup/otpScreen.dart
![otpscreen](https://github.com/venzo-tech/Saymingo/assets/104203753/93be7481-5b4a-4b0d-98db-fa75de70739d)

the bottom button should be the same height for Set pin
lib/Pages/Login & Signup/setPin.dart
![setpin](https://github.com/venzo-tech/Saymingo/assets/104203753/60281f96-2160-4644-b987-73c901808fb2)
