### ISSUE TITLE
Page Transition

### ISSUE THREAD

**Issue by Elam126** [venzo-tech/Saymingo#18]
1. The transition from Login and Signup should be from center.
2.  After sign-up flow, make the transition as ‘Fade in’.

**Comment by sivasakthi26** [comment]
#18
1.The transition from Login and Signup should be from center.
         1. lib/Pages/Login & Signup/login.dart
         2. lib/Pages/Login & Signup/signInPin.dart
         3. lib/Pages/Login & Signup/signup.dart
         4. lib/Pages/Login & Signup/otpScreen.dart
         5. lib/Pages/Login & Signup/setPin.dart

  2. After sign-up flow, make the transition as ‘Fade in’.
         1.lib/Pages/Profile/profile_page.dart
          2.lib/Pages/add_child_page.dart
          3.lib/Pages/emptyscreenimg.dart
