### ISSUE TITLE
HomePage

### ISSUE THREAD

**Issue by Elam126** [venzo-tech/Saymingo#22]
1. Childrens  should be changed to children in HomePage.
2. HomeScreen Add money Icon should be changed as per the design.

**Comment by sivasakthi26** [comment]
#22
1.Childrens should be changed to children in HomePage.
lib/Pages/home_screen.dart
![home screen](https://github.com/venzo-tech/Saymingo/assets/104203753/c93b4ebc-3548-43b5-acae-d6580468fc2c)
